global using System;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Components;
global using Toolbelt.Blazor.SpeechSynthesis;
global using System.Runtime.InteropServices;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Capybara;
global using Capybara.Components;
global using Capybara.Components.ComboInput;
global using MudBlazor.Services;
global using MudBlazor;
global using Toolbelt.Blazor.Extensions.DependencyInjection;
global using Tewr.Blazor.FileReader;
global using Capybara.Models;
global using System.Net.Http.Json;
global using ApexCharts;
global using Capybara.Components.Dialogs;
global using JiuLing.CommonLibs.ExtensionMethods;
global using Microsoft.AspNetCore.SignalR.Client;
global using Microsoft.JSInterop;
global using Capybara.Models.Enums;
global using Microsoft.AspNetCore.Components.Forms;
global using Capybara.Shared.Dialogs;
global using System.Collections.Concurrent;
global using System.Text.Json;
global using Capybara.Shared;
global using Capybara.Models.Appointment;
global using Heron.MudCalendar;
global using ZXingBlazor.Components;

global using Color = MudBlazor.Color;
global using Console = System.Console;